"""
fluxgym-pro command generator.

Pure-Python, no torch / no GPU: builds the exact training command sequence for
each architecture.

Backends (verified against upstream docs, 2026-02):
  - Z-Image        -> musubi-tuner  (zimage_cache_latents.py, zimage_train_network.py)
  - Krea 2         -> musubi-tuner  (krea2_cache_latents.py,   krea2_train_network.py)
  - Qwen-Image-2.1 -> ai-toolkit    (run.py + generated YAML; musubi-tuner has no
                                      Qwen-Image-2.1 support yet, only the older
                                      20B Qwen-Image)
"""

import os

# arch -> musubi-tuner script stems. qwen_image_2 is handled by ai-toolkit.
MUSUBI_SCRIPTS = {
    "zimage": {
        "cache_latents": "zimage_cache_latents.py",
        "cache_text": "zimage_cache_text_encoder_outputs.py",
        "train": "zimage_train_network.py",
    },
    "krea2": {
        "cache_latents": "krea2_cache_latents.py",
        "cache_text": "krea2_cache_text_encoder_outputs.py",
        "train": "krea2_train_network.py",
    },
}

# arch -> network module inside musubi-tuner's networks/ package
NETWORK_MODULE = {"zimage": "networks.lora_zimage", "krea2": "networks.lora_krea2"}

# flow-matching sampling settings per musubi arch (straight from upstream docs)
FLOW_ARGS = {
    "zimage": "--timestep_sampling shift --weighting_scheme none --discrete_flow_shift 2.0",
    "krea2": "--timestep_sampling shift --weighting_scheme none --discrete_flow_shift 2.5",
}

ARCH_LABELS = {
    "zimage": "Z-Image",
    "krea2": "Krea 2",
    "qwen_image_2": "Qwen-Image-2.1",
}


def _flow_args(cfg):
    """Build only supported flow options; preserve the documented defaults."""
    arch = cfg["arch"]
    mode = cfg.get("timestep_sampling", "Model default (recommended)")
    if mode == "Model default (recommended)":
        return FLOW_ARGS[arch].split()
    args = ["--timestep_sampling", mode, "--weighting_scheme", "none"]
    shift = float(cfg.get("flow_shift") or 0)
    if mode != "krea2_shift":
        args.extend(["--discrete_flow_shift", str(shift or (2.5 if arch == "krea2" else 2.0))])
    return args


def _ps(lines):
    """Join command lines with PowerShell continuation backticks (no dangling)."""
    return " `\n  ".join(lines)


def _ps_quote(s):
    """Quote a value as a single PowerShell argument.

    Doubles backticks and escapes double quotes so a value from the UI can
    never terminate the quoted argument or escape into code. CR/LF are
    neutralized: inside a double-quoted string a raw newline would break the
    argument (and the line) apart.
    """
    return ('"' + str(s).replace("\r\n", " ").replace("\r", " ")
            .replace("\n", " ").replace("`", "``").replace('"', '`"') + '"')


def _yaml_str(s):
    """Escape a value for a YAML double-quoted scalar (no newlines, no breaks)."""
    return (str(s).replace("\r", " ").replace("\n", " ")
            .replace("\\", "\\\\").replace('"', '\\"'))


def dataset_toml(train_dir, resolution, batch_size, repeats=1):
    """musubi-tuner dataset config (docs/dataset_config.md schema)."""
    r = f"[{resolution}, {resolution}]"
    return (
        "# generated by fluxgym-pro\n"
        "[general]\n"
        f"resolution = {r}\n"
        "caption_extension = \".txt\"\n"
        f"batch_size = {batch_size}\n"
        "\n"
        "[[datasets]]\n"
        f"image_directory = \"{os.path.abspath(os.path.join(train_dir, 'img')).replace(os.sep, '/')}\"\n"
        f"num_repeats = {repeats}\n"
    )


def _musubi_commands(cfg):
    """musubi-tuner path: cache latents -> cache text encoder outputs -> train.

    Scripts run from the musubi-tuner repo root as `python src/musubi_tuner/<script>`.
    """
    arch = cfg["arch"]
    scripts = MUSUBI_SCRIPTS[arch]
    toml = cfg["toml_path"]
    py = cfg["python_exe"]
    out_dir = cfg["output_dir"]
    out_name = cfg["output_name"]
    epochs = cfg["epochs"]
    lr = cfg["learning_rate"]
    dim = cfg["network_dim"]
    alpha = int(cfg.get("network_alpha") or dim)
    seed = cfg["seed"]
    precision = cfg.get("mixed_precision", "bf16")
    optimizer = cfg.get("optimizer", "adamw8bit")
    blocks_to_swap = max(0, int(cfg.get("blocks_to_swap") or 0))
    cache_batch_size = max(1, int(cfg.get("cache_batch_size") or 16))
    loader_workers = max(0, int(cfg.get("loader_workers") or 0))

    vae = cfg.get("vae_path")
    te = cfg.get("text_encoder_path")
    dit = cfg.get("dit_path")
    save_every = cfg.get("save_every_n_epochs", 1)
    prompts = cfg.get("sample_prompts") or []
    sample_every = int(cfg.get("sample_every") or 0)
    sampling = bool(prompts) and sample_every > 0
    prompts_path = ""
    if sampling:
        # command_gen may be called directly (tests, previews); keep its own
        # file writes safe even if the caller skipped build_cfg validation.
        fs_name = "".join(c if c not in '\\/:*?"<>|' else "_" for c in out_name)
        prompts_path = os.path.join(cfg["output_dir"],
                                    f"{fs_name}_sample_prompts.txt")
        with open(prompts_path, "w", encoding="utf-8") as f:
            for p in prompts:
                f.write(p.replace("\n", " ").strip() + "\n")

    if not (vae and os.path.exists(vae)):
        raise RuntimeError(f"VAE weights not found: {vae}")
    if not (te and os.path.exists(te)):
        raise RuntimeError(f"Text encoder weights not found: {te}")
    if not (dit and os.path.exists(dit)):
        raise RuntimeError(f"DiT weights not found: {dit}")

    cache_lat = _ps([f"{py}", "src/musubi_tuner/" + scripts["cache_latents"],
                     "--dataset_config", _ps_quote(toml), "--vae", _ps_quote(vae)])
    cache_te = _ps([f"{py}", "src/musubi_tuner/" + scripts["cache_text"],
                    "--dataset_config", _ps_quote(toml), "--text_encoder", _ps_quote(te),
                    "--batch_size", str(cache_batch_size)])
    train = _ps([
        "accelerate launch --num_cpu_threads_per_process 1 --mixed_precision " + precision,
        "src/musubi_tuner/" + scripts["train"],
        "--dit", _ps_quote(dit),
        "--vae", _ps_quote(vae),
        # krea2 only needs the TE during training if sample images are generated
        *(["--text_encoder", _ps_quote(te)] if (arch != "krea2" or sampling) else []),
        "--dataset_config", _ps_quote(toml),
        "--sdpa --mixed_precision", precision,
        *(["--fp8_base --fp8_scaled"] if cfg.get("fp8_base") else []),
        *(["--fp8_llm"] if cfg.get("fp8_llm") else []),
        *(["--convrot_int8"] if cfg.get("convrot_int8") else []),
        *_flow_args(cfg),
        "--optimizer_type", optimizer,
        *(["--optimizer_args", *[_ps_quote(arg) for arg in cfg.get("optimizer_args", [])]]
          if cfg.get("optimizer_args") else []),
        "--learning_rate", str(lr),
        "--lr_scheduler", cfg.get("lr_scheduler", "constant"),
        "--lr_warmup_steps", str(max(0, int(cfg.get("lr_warmup_steps") or 0))),
        "--max_grad_norm", str(max(0, float(cfg.get("max_grad_norm") or 0))),
        "--gradient_checkpointing",
        *(["--gradient_checkpointing_cpu_offload"]
          if cfg.get("gradient_checkpointing_cpu_offload") else []),
        *( ["--blocks_to_swap", str(blocks_to_swap), "--block_swap_optimizer_patch_params"]
           if blocks_to_swap and optimizer != "adafactor" else []),
        *( ["--blocks_to_swap", str(blocks_to_swap), "--fused_backward_pass"]
           if blocks_to_swap and optimizer == "adafactor" else []),
        *(["--full_bf16"] if cfg.get("full_bf16") else []),
        *(["--fused_backward_pass"]
          if cfg.get("full_bf16") and not blocks_to_swap else []),
        "--gradient_accumulation_steps", str(max(1, int(cfg.get("gradient_accumulation_steps") or 1))),
        "--max_data_loader_n_workers", str(loader_workers),
        *(["--persistent_data_loader_workers"]
          if cfg.get("persistent_workers") and loader_workers else []),
        "--network_module", NETWORK_MODULE[arch],
        "--network_dim", str(dim),
        "--network_alpha", str(alpha),
        "--max_train_epochs", str(epochs),
        "--save_every_n_epochs", str(save_every),
        "--save_precision", cfg.get("save_precision", "bf16"),
        *(["--save_state"] if cfg.get("save_state") else []),
        *(["--mem_eff_save"] if cfg.get("mem_eff_save") else []),
        *(["--guidance_scale", str(cfg.get("guidance_scale"))]
          if float(cfg.get("guidance_scale") or 0) > 0 else []),
        *(["--sample_prompts", _ps_quote(prompts_path), "--sample_every_n_epochs", str(sample_every)]
          if sampling else []),
        "--seed", str(seed),
        "--output_dir", _ps_quote(out_dir),
        "--output_name", _ps_quote(out_name),
    ])

    body = (
        f'Write-Host "=== [1/3] caching latents ({ARCH_LABELS[arch]}) ==="\n'
        f"{cache_lat}\n"
        f'if ($LASTEXITCODE -ne 0) {{ throw "latent caching failed" }}\n\n'
        f'Write-Host "=== [2/3] caching text encoder outputs ==="\n'
        f"{cache_te}\n"
        f'if ($LASTEXITCODE -ne 0) {{ throw "text encoder caching failed" }}\n\n'
        f'Write-Host "=== [3/3] training LoRA ==="\n'
        f"{train}\n"
        f'if ($LASTEXITCODE -ne 0) {{ throw "training failed" }}\n\n'
        f'Write-Host "DONE: {out_dir}\\{out_name}.safetensors"\n'
    )
    return body, "musubi-tuner"


def _atk_yaml(cfg):
    """ai-toolkit training config for Qwen-Image-2.1 (day-0 upstream support).

    Schema mirrors ai-toolkit's sd_trainer examples: job=extension, one
    sd_trainer process, model.arch selects the architecture implementation.
    """
    arch = "qwen_image_2"
    base_repo = cfg["repo"]
    train_dir = cfg["train_data_dir"].replace("\\", "/") + "/img"
    out_dir = cfg["output_dir"].replace("\\", "/")
    out_name = cfg["output_name"]
    lr = cfg["learning_rate"]
    dim = cfg["network_dim"]
    save_every = cfg.get("save_every_n_epochs", 250)
    res = cfg["resolution"]
    bs = cfg["batch_size"]
    accumulation = max(1, int(cfg.get("gradient_accumulation_steps") or 1))
    quantize = "true" if cfg.get("quantize", True) else "false"
    quantize_te = "true" if cfg.get("quantize_te", True) else "false"
    low_vram = "true" if cfg.get("low_vram", True) else "false"
    seed = cfg["seed"]
    steps = int(cfg.get("steps") or 0) or int(cfg["epochs"]) * 100

    triggers = [t.strip() for t in cfg.get("trigger", "").split(",") if t.strip()]
    trigger = triggers[0] if triggers else ""

    # sample prompts: fluxgym-style textarea -> upstream sample: block (steps-based)
    prompts = cfg.get("sample_prompts") or []
    sample_every = int(cfg.get("sample_every") or 0)
    steps_per_epoch = max(1, steps // max(1, int(cfg["epochs"])))
    if prompts and sample_every > 0:
        yaml_lines = "\n".join(f'          - "{_yaml_str(p)}"' for p in prompts)
        sample_block = f"""      sample:
        sampler: "flowmatch" # must match train.noise_scheduler
        sample_every: {steps_per_epoch * sample_every}
        sample_start_step: 0
        width: {res}
        height: {res}
        prompts:
{yaml_lines}
        neg: ""
        seed: {seed}
        walk_seed: true
        guidance_scale: 3
        sample_steps: 25
"""
    else:
        sample_block = ""

    return f"""job: extension
config:
  name: "{_yaml_str(out_name)}"
  process:
    - type: sd_trainer
      training_folder: "{_yaml_str(out_dir)}"
      device: cuda:0{f'\n      trigger_word: "{_yaml_str(trigger)}"' if trigger else ""}
      network:
        type: lora
        linear: {dim}
        linear_alpha: {dim}
      save:
        dtype: float16
        save_every: {save_every}
        max_step_saves_to_keep: 4
      datasets:
        - folder_path: "{_yaml_str(train_dir)}"
          caption_ext: "txt"
          caption_dropout_rate: 0.05
          shuffle_tokens: false
          cache_latents_to_disk: true
          resolution: [{res}, {res}]
      train:
        batch_size: {bs}
        steps: {steps}
        gradient_accumulation: {accumulation}
        # caching text embeddings is required for 24GB cards
        cache_text_embeddings: true
        train_unet: true
        train_text_encoder: false
        gradient_checkpointing: true
        noise_scheduler: "flowmatch"
        optimizer: "adamw8bit"
        lr: {lr}
        seed: {seed}
        dtype: bf16
{sample_block}      model:
        name_or_path: "{base_repo}"
        arch: "{arch}"
        quantize: {quantize}
        quantize_te: {quantize_te}
        qtype_te: "qfloat8"
        low_vram: {low_vram}
"""


def _atk_commands(cfg):
    """ai-toolkit path: embed the YAML in the script, run.py, report output."""
    py = cfg["python_exe"]
    atk = cfg["backend_dir"]
    yaml_path = os.path.join(cfg["output_dir"], cfg["output_name"] + ".atk.yml")
    out_dir = cfg["output_dir"]
    out_name = cfg["output_name"]

    yaml_text = _atk_yaml(cfg)
    # single-quoted here-string: PowerShell does no interpolation, YAML stays verbatim
    write = (
        "@'\n"
        f"{yaml_text}"
        "\n'@ | Set-Content -Encoding UTF8 \"" + yaml_path.replace('"', '`"') + "\"\n"
    )
    run = _ps([f"{py}", "run.py", _ps_quote(yaml_path)])
    body = (
        f'Write-Host "=== training Qwen-Image-2.1 LoRA (ai-toolkit) ==="\n'
        f"{write}\n"
        f"{run}\n"
        f'if ($LASTEXITCODE -ne 0) {{ throw "training failed" }}\n\n'
        f'Write-Host "DONE: {out_dir}\\{out_name}.safetensors"\n'
    )
    return body, "ai-toolkit"


def build_commands(cfg):
    """Route to the right backend and return (script_body, backend_label)."""
    if cfg["arch"] in MUSUBI_SCRIPTS:
        return _musubi_commands(cfg)
    if cfg["arch"] == "qwen_image_2":
        return _atk_commands(cfg)
    raise RuntimeError(f"Unknown architecture: {cfg['arch']}")


def full_script(cfg):
    body, backend = build_commands(cfg)
    header = (
        f"# fluxgym-pro :: {ARCH_LABELS[cfg['arch']]} LoRA :: {cfg['output_name']}\n"
        f"# backend: {backend}\n"
        f"# generated by fluxgym-pro — edit values in the UI, not here\n"
        f"$ErrorActionPreference = 'Stop'\n"
        f"Set-Location {_ps_quote(cfg['backend_dir'])}\n\n"
    )
    return header + body
